### ISSUE TITLE
 [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。

### ISSUE THREAD

**Issue by MasterOfStar** [NewFuture/DDNS#123]
```
2020-01-17 19:28:50,034 <cache.load> 62@util\cache.py
[INFO] cache file not exist
2020-01-17 19:28:50,035 <run.main> 182@run.py
[WARNING] Cache file is out of dated.
Traceback (most recent call last):
  File "run.py", line 189, in <module>
  File "run.py", line 185, in main
  File "run.py", line 132, in update_ip
  File "run.py", line 103, in get_ip
  File "util\ip.py", line 32, in default_v6
OSError: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。
[20232] Failed to execute script run
```
json：
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "隐私保护",
  "index4": "false",
  "index6": "default",
  "ipv4": [],
  "ipv6": [
    "域名"
  ],
  "proxy": null,
  "token": "隐私保护",
  "ttl": null
}
```

**Comment by NewFuture** [comment]
网络问题，是否恢复？
