### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by qiangwushuang** [NewFuture/DDNS#145]
### version info [基本信息]

* DDNS Version: v2.8.1@2020-01-14T05:50:10+00:00
* OS Version： Openwrt
* Type(运行方式): Python
* related issues (相关问题): 
 无法更新，程序卡住，未生成记录。

下面id处使用登陆邮箱，token使用cloudflare ```Edit zone DNS``` 模板创建
### config file 
```{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "cloudflare",
  "id": "xxx",
  "index4": "default",
  "index6": "default",
  "ipv4": ["router.devfun.pw"],
  "ipv6": [],
  "token": "xxx"
}
```

###  debug output [调试输出]
```sh
[WARNING] Cache file is out of dated.

***(A) ==> *** [via DIRECT]
2020-03-10 13:41:12,244 <cloudflare.update_record> 127@/usr/lib/python3.7/site-packages/dns/cloudflare.py
[INFO] >>>>>***(A)
2020-03-10 13:41:12,245 <cloudflare.request> 44@/usr/lib/python3.7/site-packages/dns/cloudflare.py
[INFO] api.cloudflare.com/ : {'per_page': 50}
^CTraceback (most recent call last):
  File "/usr/bin/ddns", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/run.py", line 184, in main
    update_ip('4', cache, dns, proxy_list)
  File "/usr/lib/python3.7/site-packages/run.py", line 141, in update_ip
    if change_dns_record(dns, proxy_list, domain=domain, ip=address, record_type=record_type):
  File "/usr/lib/python3.7/site-packages/run.py", line 118, in change_dns_record
    return dns.update_record(domain, kw['ip'], record_type=record_type)
  File "/usr/lib/python3.7/site-packages/dns/cloudflare.py", line 128, in update_record
    zoneid = get_zone_id(domain)
  File "/usr/lib/python3.7/site-packages/dns/cloudflare.py", line 86, in get_zone_id
    zones = request('GET', '', per_page=50)
  File "/usr/lib/python3.7/site-packages/dns/cloudflare.py", line 63, in request
    conn.request(method, '/client/v4/zones' + action, params, headers)
  File "/client.py", line 1252, in request
  File "/client.py", line 1298, in _send_request
  File "/client.py", line 1247, in endheaders
  File "/client.py", line 1026, in _send_output
  File "/client.py", line 966, in send
  File "/client.py", line 1414, in connect
  File "/client.py", line 938, in connect
  File "/socket.py", line 716, in create_connection
KeyboardInterrupt
```

**Comment by NewFuture** [comment]
超时了？ cloudflare API 能正常访问吗？

**Comment by qiangwushuang** [comment]
通过下面测试是可以获取到zone信息的，ping也能通。
```sh
curl -X GET "https://api.cloudflare.com/client/v4/zones" \
    -H "X-Auth-Email: xxx" \
    -H "X-Auth-Key: xxx" \
    -H "Content-Type: application/json"
```

**Comment by NewFuture** [comment]
现在正常了么?

**Comment by qiangwushuang** [comment]
抱歉，最近搬家，网络还没有弄好，周末测试后反馈

**Comment by qiangwushuang** [comment]
抱歉，最近搬家，网络还没有弄好，周末测试后反馈

**Comment by qiangwushuang** [comment]
可以使用了，谢谢！

**Comment by laozhoubuluo** [comment]
这个应该就是您网络到 api.cloudflare.com 的连接质量本身比较差，导致几率性出现连接不上（您这里看报错就是socket连接失败了）、无法握手或者连接上之后断掉（域名列表这个json有时候比较长，也加剧了此问题）的情况，因此可能导致程序卡住、DNS更新失败等异常情况。
建议在DDNS的机器上配一个代理，完了让DDNS软件走代理服务器连接，可能会有所改善。
