### ISSUE TITLE
vmware ESXi 7运行报错

### ISSUE THREAD

**Issue by bg4hkq** [NewFuture/DDNS#234]
使用的是linux二进制版，用于更新alidns。
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "id": "xxxx",
  "token": "xxxx",
  "dns": "alidns",
  "ipv4": ["vms.baoz.info"],
  "ipv6": [],
  "index4": 0,
  "index6": "public",
  "ttl": 600,
  "proxy": "DIRECT",
  "debug": true
}
```

```
DDNS[ v2.9.8@2021-02-22T01:50:23+00:00 ] run: posix linux
Configuration was loaded from <== /vmfs/volumes/603d5cb9-1925321d-4372-1c697a665589/tools/config.json
========================= Wed Mar 17 19:19:25 2021 =========================
2021-03-17 19:19:25,883 <cache.load> 48@util/cache.py
[DEBUG] load cache data from /tmp/ddns.cache
2021-03-17 19:19:25,883 <run.main> 190@run.py
[WARNING] Cache file is out of dated.
2021-03-17 19:19:25,884 <ip.local_v4> 45@util/ip.py
[DEBUG] [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.10.131', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('192.168.10.131', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('192.168.10.131', 0))]

vms.baoz.info(A) ==> 192.168.10.131 [via DIRECT]
2021-03-17 19:19:25,884 <alidns.update_record> 147@dns/alidns.py
[DEBUG] >>>>>vms.baoz.info(A)
2021-03-17 19:19:25,885 <alidns.signature> 57@dns/alidns.py
[DEBUG] AccessKeyId=lKIOE6shQQWOGwGf&Action=GetMainDomainName&Format=json&InputString=vms.baoz.info&SignatureMethod=HMAC-SHA1&SignatureNonce=6d55bd63-d10b-405c-9999-4766293f52e9&SignatureVersion=1.0&Timestamp=2021-03-17T19%3A19%3A25Z&Version=2015-01-09
2021-03-17 19:19:25,885 <alidns.signature> 59@dns/alidns.py
[DEBUG] signString: POST&%2F&AccessKeyId%3DlKIOE6shQQWOGwGf%26Action%3DGetMainDomainName%26Format%3Djson%26InputString%3Dvms.baoz.info%26SignatureMethod%3DHMAC-SHA1%26SignatureNonce%3D6d55bd63-d10b-405c-9999-4766293f52e9%26SignatureVersion%3D1.0%26Timestamp%3D2021-03-17T19%253A19%253A25Z%26Version%3D2015-01-09
2021-03-17 19:19:25,885 <alidns.request> 76@dns/alidns.py
[INFO] alidns.aliyuncs.com: {'Action': 'GetMainDomainName', 'InputString': 'vms.baoz.info', 'Format': 'json', 'Version': '2015-01-09', 'AccessKeyId': 'lKIOE6shQQWOGwGf', 'Timestamp': '2021-03-17T19:19:25Z', 'SignatureMethod': 'HMAC-SHA1', 'SignatureNonce': UUID('6d55bd63-d10b-405c-9999-4766293f52e9'), 'SignatureVersion': '1.0', 'Signature': b'g5oEwIxqTGRVRbJ204HlH4oSkCo='}
Traceback (most recent call last):
  File "socket.py", line 716, in create_connection
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 199, in <module>
  File "run.py", line 194, in main
  File "run.py", line 149, in update_ip
  File "run.py", line 124, in change_dns_record
  File "dns/alidns.py", line 148, in update_record
  File "dns/alidns.py", line 104, in get_domain_info
  File "dns/alidns.py", line 84, in request
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "http/client.py", line 1384, in connect
  File "http/client.py", line 928, in connect
  File "socket.py", line 716, in create_connection
KeyboardInterrupt
[527626] Failed to execute script run
2021-03-17 19:19:35,094 <cache.sync> 85@util/cache.py
[DEBUG] save cache data to /tmp/ddns.cache
```

**Comment by NewFuture** [comment]
连接阿里云DNS服务器超时了

**Comment by bg4hkq** [comment]
> 连接阿里云DNS服务器超时了

对，我ping了一下源码里的api服务器，是可以通的。wget也能报回来400，说明网络层没问题，怀疑是不是esxi的socket底层就不一样。

**Comment by NewFuture** [comment]
还能复现可再打开
