### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by qq173972819** [NewFuture/DDNS#235]
系统：win server 2019
二进制ddns
配置：
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "dnspod",
  "id": "******",
  "index4": ["public"]
  "index6": false
  "ipv4": [
    "nas.insane.vip"
  ],
  "ipv6": [],
  "proxy": null,
  "token": "******",
  "ttl": 600
  "cache": false
}
```
报错：
```
newfuture.cc(A) ==> 192.168.2.2 [via DIRECT]
ERROR:root:invalid domain: [ newfuture.cc ]

ddns.newfuture.cc(A) ==> 192.168.2.2 [via DIRECT]
ERROR:root:invalid domain: [ ddns.newfuture.cc ]
Traceback (most recent call last):
  File "run.py", line 199, in <module>
  File "run.py", line 195, in main
  File "run.py", line 139, in update_ip
  File "run.py", line 109, in get_ip
  File "util\ip.py", line 31, in default_v6
OSError: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。
[352] Failed to execute script run
```

**Comment by NewFuture** [comment]
运行的不是这个配置吧？
