### ISSUE TITLE
[debug]

### ISSUE THREAD

**Issue by xiaobinxxx** [NewFuture/DDNS#265]
## **Describe the bug [描述]**
源码环境运行出错，不知道什么原因，是我配置错了吗？

### version info [基本信息]
源码运行出错
* DDNS Version:  
* OS Version： centos 7.9
* Type(运行方式): Binary/Python   python 2.7
* related issues (相关问题): 

### config file [配置文件]

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json", 
  "debug": false, 
  "dns": "alidns", 
  "id": "xxxx", 
  "index4": "public", 
  "index6": "default", 
  "ipv4": [
    "nw.fghdf.top", 
    "nwbt.fghdf.top"
  ], 
  "ipv6": [
    "nw.fghdf.top", 
    "nwbt.fghdf.top"
  ], 
  "proxy": "127.0.0.1:1080;DIRECT", 
  "token": "xxxx", 
  "ttl": 600
}
```

###  debug output [调试输出]

```sh
Traceback (most recent call last):
  File "./run.py", line 199, in <module>
    main()
  File "./run.py", line 195, in main
    update_ip('6', cache, dns, proxy_list)
  File "./run.py", line 139, in update_ip
    address = get_ip(ip_type, index_rule)
  File "./run.py", line 109, in get_ip
    value = getattr(ip, index + "_v" + ip_type)()
  File "/DDNS/util/ip.py", line 31, in default_v6
    s.connect(('1:1:1:1:1:1:1:1', 8))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 101] Network is unreachable
```

**Additional context**

**Comment by NewFuture** [comment]
运行的机器没用ipv6网络？
