### ISSUE TITLE
[debug]无法运行

### ISSUE THREAD

**Issue by originalFactor** [NewFuture/DDNS#390]
## **描述问题 (Describe the bug)**
配置文件修改完毕后无法运行

## 版本信息 (version info)

* DDNS Version: v2.12.0@2022-12-07T12:11:57+00:00
* OS Version： Windows 10 22H2
* Type(运行方式): Python3.11.1
* related issues (相关问题): 

## **复现步骤 (To Reproduce)**
1. 运行`python config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/`
2. 运行`pip install ddns`
3. 在`%USERPROFILE%/DESKTOP/DDNS`运行`ddns`，配置模板成功生成。
4. 在dnspod申请了id和token
5. 填写配置文件
6. 再次运行`ddns`
7. 报错（Python报错）

### 配置文件 (config file)

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "dnspod",
  "id": "123456",（非真实）
  "index4": "url:https://ip.sb",
  "index6": "default",
  "ipv4": [],
  "ipv6": [
    "mypc.example.com"（非真实）
  ],
  "proxy": null,
  "token": "abcdefghijklmnopqrstuvwxyz012345",（非真实）
  "ttl": null
}
```

### 调试输出 (debug output)

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python311\Scripts\ddns.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python311\Lib\site-packages\run.py", line 121, in main
    dns = getattr(__import__('dns', fromlist=[dns_provider]), dns_provider)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dns' has no attribute 'dnspod'
```
根本没有输出……直接python报错……我是不是下到假的了……

## 补充说明 (Additional context)

没有补充说明

**Comment by NewFuture** [comment]
pip版本的早已fix
