### ISSUE TITLE
[debug]Windows二进制运行报错

### ISSUE THREAD

**Issue by RookieTerry** [NewFuture/DDNS#391]
## **描述问题 (Describe the bug)**

如题

## 版本信息 (version info)

* DDNS Version: 2.11.5
* OS Version： Win10工作站专业版
* Type(运行方式): Binary
* related issues (相关问题): 无法读取相同目录下自定义配置文件

## **复现步骤 (To Reproduce)**
电脑没有安装Python环境，在cmd命令行下运行："C:\\Users\\xxx\\AppData\\Local\\ddns.exe" -c "C:\\Users\\xxx\\AppData\\Local\\config.json"，其中配置文件和`ddns.exe`在同一目录下。

### 配置文件 (config file)
```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": false,
  "dns": "cloudflare",
  "index4": "url:https://myip4.ipip.net/",
  "index6": "url:https://myip6.ipip.net/",
  "ipv4": [
    "myurl"
  ],
  "ipv6": [
    "myurl",
  ],
  "proxy": null,
  "token": "mytoken",
  "ttl": null
}
```

### 调试输出 (debug output)
```sh
ERROR:root: Config file `config.json` does not exist!
Traceback (most recent call last):
  File "util\config.py", line 74, in __load_config
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 159, in <module>
  File "run.py", line 120, in main
  File "util\config.py", line 64, in init_config
  File "util\config.py", line 82, in __load_config
PermissionError: [Errno 13] Permission denied: 'config.json'
[10576] Failed to execute script 'run' due to unhandled exception!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
ValueError: underlying buffer has been detached
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
```

**Comment by NewFuture** [comment]
当前文件夹没有写权限
