### ISSUE TITLE
[debug]Win10 报错 [ERROR] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

### ISSUE THREAD

**Issue by lovelyelfpop** [NewFuture/DDNS#416]
## 版本信息 (version info)

* DDNS Version: 2.13.3
* OS Version： windows 10 build 19041
* Type(运行方式): Binary/
* related issues (相关问题): 

### 配置文件 (config file)

```json
{
  "$schema": "https://ddns.newfuture.cc/schema/v2.8.json",
  "debug": true,
  "dns": "he",
  "id": "",
  "index4": "url:http://ip.3322.net/",
  "index6": "public",
  "ipv4": [
    "hexapus.cn"
  ],
  "ipv6": [
  ],
  "proxy": null,
  "token": "****************",
  "ttl": null,
  "cache": false
}
```

### 调试输出 (debug output)

```sh
[INFO] Cache is disabled!
2024-01-22 16:02:45,398 <ip._open> 51@util\ip.py
[DEBUG] open: http://ip.3322.net/
2024-01-22 16:02:45,428 <ip._open> 55@util\ip.py
[DEBUG] response: 153.35.129.225

2024-01-22 16:02:45,428 <he.update_record> 77@dns\he.py
[INFO] >>>>>hexapus.cn(A)
2024-01-22 16:02:45,428 <he.request> 44@dns\he.py
[INFO] dyn.dns.he.net/nic/update : {'hostname': 'hexapus.cn', 'myip': '153.35.129.225', 'password': '***'}
2024-01-22 16:02:45,631 <run.change_dns_record> 83@run.py
[ERROR] [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ValueError: underlying buffer has been detached
```

**Comment by NewFuture** [comment]
#484 自动加载系统路径和跳过验证
