### ISSUE TITLE
麻烦您更新下指定网卡获取公网ipv6地址

### ISSUE THREAD

**Issue by huangmengsheng** [NewFuture/DDNS#53]
"index6":  "public",
改为
"index6":  2,
会报
Traceback (most recent call last):
  File "run.py", line 151, in <module>
  File "run.py", line 147, in main
  File "run.py", line 104, in update_ip
  File "run.py", line 71, in get_ip
  File "util/ip.py", line 32, in local_v6
  File "socket.py", line 748, in getaddrinfo
socket.gaierror: [Errno -2] Name or service not known
[22422] Failed to execute script run

**Comment by NewFuture** [comment]
> socket.gaierror: [Errno -2] Name or service not known

这似乎是系统网络配置的问题

**Comment by huangmengsheng** [comment]
> socket.gaierror: [Errno -2] Name or service not known
> 
> 这似乎是系统网络配置的问题
设置
"index4": 2,
正常的

**Comment by NewFuture** [comment]
本机名ipv6地址解析是不是没有配

**Comment by huangmengsheng** [comment]
待会回家以后看看！
